project:
  type: website
  output-dir: docs

website:
  title: "STA3111 Theory of Estimation"
  favicon: "files/imgfile.png"
  page-footer: 
    left: |
        Copyright 2024, Mutua Kilai <br> With inspiration from template created by [Andrew Heiss](https://www.andrewheiss.com/) 
    right: |
        Made with {{< fa brands r-project >}},<i class="fa-solid fa-heart"></i>, and [Quarto](https://quarto.org/)<br>
  navbar:
    background: "#00ff99"
    right:
      - text: "Course Description"
        file: index.qmd
      - text: "Lecture Notes"
        file: lectures.qmd
      - text: "Exercises"
        file: solutions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

